<a href="https://colab.research.google.com/github/xanasa14/Finances/blob/main/Forecasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [17]:
import pandas as pd
import plotly.express as px
from copy import copy
from scipy import stats
import matplotlib.pyplot as plt
import numpy as np
import plotly.figure_factory as ff
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from tensorflow import keras
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [8]:
# Read stock prices data
#stock_price_df = pd.read_csv('/content/drive/MyDrive/MLFinancial/Part 3. AI and ML in Finance/stock.csv')
stock_price_df = pd.read_csv('/content/drive/MyDrive/YahooData/YahooFinanceData.csv')
stock_price_df

           Date         MMM        AOS  ...         ZBH       ZION         ZTS
0    2018-01-02  235.639999  61.529999  ...  124.059998  50.700001   71.769997
1    2018-01-03  235.630005  61.900002  ...  124.919998  50.639999   72.099998
2    2018-01-04  238.710007  62.189999  ...  124.739998  50.849998   72.529999
3    2018-01-05  240.570007  62.990002  ...  125.980003  50.869999   73.360001
4    2018-01-08  239.789993  63.290001  ...  126.220001  50.619999   74.239998
..          ...         ...        ...  ...         ...        ...         ...
789  2021-02-22  176.119995  61.849998  ...  160.339996  53.360001  160.160004
790  2021-02-23  176.169998  61.759998  ...  161.869995  54.169998  159.520004
791  2021-02-24  177.630005  61.299999  ...  163.690002  56.779999  159.050003
792  2021-02-25  178.759995  60.230000  ...  164.500000  54.570000  156.479996
793  2021-02-26  175.059998  59.369999  ...  163.059998  53.169998  155.240005

[794 rows x 398 columns]

In [56]:
df = stock_price_df[['AMD']]
days = 1
df['prediction'] = df['AMD'].shift(-1)
df.dropna(inplace=True)

forecast_time = int(days)

In [57]:
df

           AMD  prediction
0    10.980000   11.550000
1    11.550000   12.120000
2    12.120000   11.880000
3    11.880000   12.280000
4    12.280000   11.820000
..         ...         ...
788  89.580002   85.370003
789  85.370003   84.739998
790  84.739998   86.940002
791  86.940002   82.419998
792  82.419998   84.510002

[793 rows x 2 columns]

In [58]:
#Predicting the Stock price in the future
X = np.array(df.drop(['prediction'], 1))
Y = np.array(df['prediction'])

scaler = preprocessing.StandardScaler().fit(X)
X = scaler.transform(X)

#X = preprocessing.scale(X)
X_prediction = X[-forecast_time:]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25)

In [59]:
 #Performing the Regression on the training data
clf = LinearRegression()
clf.fit(X_train, Y_train)
xtx = (clf.predict(X_prediction))

last_row = df.tail(1)
lr_accuracy = clf.score(X_test, Y_test)
print("Linear Regression Score: ", lr_accuracy)
print(last_row['AMD'])

Linear Regression Score:  0.9962990257186852
792    82.419998
Name: AMD, dtype: float64

In [60]:
xtx

array([82.45750201])

In [61]:
x = scaler.inverse_transform(X_prediction)
x

array([[82.41999817]])